export enum ButtonValue {
  C = 'C',
  Percent = '%',
  PlusMinus = '+/-',
  Seven = '7',
  Eight = '8',
  Nine = '9',
  Four = '4',
  Five = '5',
  Six = '6',
  One = '1',
  Two = '2',
  Three = '3',
  Zero = '0',
  Decimal = '.',
  Divide = '/',
  Multiply = '*',
  Subtract = '-',
  Add = '+',
  Equal = '=',
}
